2022-12-28 14:13:21,865 werkzeug     INFO     [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:1050
2022-12-28 14:13:21,865 werkzeug     INFO     [33mPress CTRL+C to quit[0m
2022-12-28 14:13:24,411 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\routes.py", line 10, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\templates\main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\templates\base.html", line 16, in top-level template code
    {{ toastr.include_jquery() }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\jinja2\environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'toastr' is undefined
2022-12-28 14:13:24,568 werkzeug     INFO     127.0.0.1 - - [28/Dec/2022 14:13:24] "[35m[1mGET / HTTP/1.1[0m" 500 -
2022-12-28 14:13:24,605 werkzeug     INFO     127.0.0.1 - - [28/Dec/2022 14:13:24] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-28 14:15:04,674 werkzeug     INFO     [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:1201
2022-12-28 14:15:04,674 werkzeug     INFO     [33mPress CTRL+C to quit[0m
2022-12-28 14:15:05,037 app          ERROR    Exception on / [GET]
Traceback (most recent call last):
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\routes.py", line 10, in index
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\templates\main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\templates\base.html", line 27, in top-level template code
    {% include "_createtask.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\glh-tracker\app\templates\_createtask.html", line 9, in top-level template code
    <form action="{{ url_for('add_task') }}" id="new-task" method="POST">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\flask\app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programming\Python\Projects\hdev-glh-tracker\venv\Lib\site-packages\werkzeug\routing\map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'add_task'. Did you mean 'static' instead?
2022-12-28 14:15:05,117 werkzeug     INFO     127.0.0.1 - - [28/Dec/2022 14:15:05] "[35m[1mGET / HTTP/1.1[0m" 500 -
2022-12-28 14:15:05,146 werkzeug     INFO     127.0.0.1 - - [28/Dec/2022 14:15:05] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2022-12-28 18:56:20,655 waitress     INFO     Serving on http://0.0.0.0:27546
2022-12-28 18:57:47,448 waitress     INFO     Serving on http://0.0.0.0:27592
2022-12-28 19:01:52,563 waitress     INFO     Serving on http://0.0.0.0:21950
2022-12-28 19:04:28,338 waitress     INFO     Serving on http://0.0.0.0:1034
2022-12-28 19:07:04,918 waitress     INFO     Serving on http://0.0.0.0:1172
